shell fish

include keybinds.conf
include theme.conf

enabled_layouts splits
tab_bar_style custom
tab_separator "|"
tab_bar_align left
tab_activity_symbol ""
tab_title_max_length 20
tab_title_template "{index}:{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.progress_percent}{title}"

bell_on_tab 󰂟
enable_audio_bell no
visual_bell_color #414866
visual_bell_duration 0.05
