pulse.rules = [
  {
    matches = [
      { application.process.binary = "vesktop" }
      { application.process.binary = "helium" }
      # possible app names, maybe incorrect
      { application.process.binary = "Discord" }
      { application.process.binary = "chromium" }
      { application.process.binary = "chrome" }
      { application.process.binary = "MicrosoftTeams" }
      { application.process.binary = "Slack" }
      { application.process.binary = "Telegram" }
      { application.process.binary = "WhatsApp" }
      { application.process.binary = "WhatsAppDesktop" }
      { application.process.binary = "WebCord" }
      { application.process.binary = "BetterDiscord" }
      { application.process.binary = "Element" }
      { application.process.binary = "Signal" }
    ]
    actions = { quirks = [ block-source-volume block-sink-volume ] }
  }
]
