gpu-context=wayland
profile=gpu-hq
vo=gpu
hwdec=auto-safe
keep-open=yes

# don't use av1 (not supported on t480s)
ytdl-format=bestvideo[height<=1080][vcodec^=vp9]+bestaudio/best

title=${filename} - mpv

# uosc compatibility
osd-bar=no
border=no
