#!/usr/bin/env bash

input_paths=(
	"~/stuff/projects"
	"~/dotfiles/.config"
	"~/Documents/nure/semester-4"
)

ignored_names=(
	".git"
	"target"
	"build"
	"__pycache__"
	"venv"
)

if [ -x "$(command -v fd)" ]; then
	find_command="fd ."
	find_opts=(--type d --max-depth 1)
else
	find_command="find"
	find_opts=(-mindepth 1 -maxdepth 1 -type d)
fi

expanded_paths=("${input_paths[@]/#\~/$HOME}")
all_subdirs=$($find_command "${expanded_paths[@]}" "${find_opts[@]}")$'\n'

exclude_pattern=$(printf "/%s$\n" "${ignored_names[@]}" | paste -sd '|')

selected_path=$(echo -e "$all_subdirs" | sed 's|/$||' | grep . | grep -vE "$exclude_pattern" | sed "s|^$HOME|~|" | fzf --height 100%)

if [[ -z $selected_path ]]; then
	exit 0
fi

selected_path=$(readlink -f "${selected_path/#\~/$HOME}")
session_name=$(basename "$selected_path" | tr '.' '_')

if [[ -z $ZELLIJ ]]; then
	cd $selected_path

	zellij attach $session_name -c
	exit 0
fi

zellij pipe --plugin switch -- "--session $session_name --cwd $selected_path --layout default"
